CREATE TABLE `t_goods` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tbId` varchar(20) NOT NULL COMMENT '商品id',
  `goodName` varchar(255) NOT NULL COMMENT '商品名称',
  `mainPicUrl` varchar(500) DEFAULT NULL COMMENT '主图地址',
  `viewUrl` varchar(500) DEFAULT NULL COMMENT '详情地址',
  `category` varchar(255) DEFAULT NULL COMMENT '一级类目',
  `tbkUrl` varchar(255) DEFAULT NULL COMMENT '淘宝客url',
  `price` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '价格',
  `monthSales` int(10) DEFAULT 0 COMMENT '月销量',
  `incomeRatio` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '收入比例',
  `commision` decimal(8,2) unsigned DEFAULT '0.00' COMMENT '佣金',
  `sellerName` varchar(255) DEFAULT NULL COMMENT '卖家名称',
  `sellerId` varchar(20) DEFAULT NULL COMMENT '卖家ID',
  `shopName` varchar(255) DEFAULT NULL COMMENT '店铺名称',
  `platform` varchar(20) DEFAULT NULL COMMENT '平台',
  `couponId` varchar(64) DEFAULT NULL COMMENT '优惠券ID',
  `couponTotal` int(10) unsigned DEFAULT '0' COMMENT '优惠券总量',
  `couponSurplus` int(10) unsigned DEFAULT '0' COMMENT '优惠券剩余量',
  `couponName` varchar(255) DEFAULT NULL COMMENT '优惠券名称',
  `couponsStartTime` date DEFAULT NULL COMMENT '优惠券开始时间',
  `couponsEndTime` date DEFAULT NULL COMMENT '优惠券结束时间',
  `couponsUrl` varchar(255) DEFAULT NULL COMMENT '优惠券链接',
  `couponsExtensionUrl` varchar(512) DEFAULT NULL COMMENT '商品优惠券推广链接',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;